@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoidGlhcmFAdGlhcmEuY29tIiwiY29udGFjdG8iOjk4NzY1NDMyMSwiaWF0IjoxNzY2MDIyNzU0LCJleHAiOjE3NjYwMjYzNTR9.RHhaLi86oyrDCqPLQRRANon-evmdzNNtZGwcso922_g

###Obtener todas las publicaciones
POST http://localhost:3000/pets/auth/login
Content-Type: application/json

{
    "email": "maria@gomez.com",
    "password": "pass123"
}

###Registro de usuario
POST http://localhost:3000/pets/auth/register
Content-Type: application/json

{
    "us_nombre": "Tiara",
    "us_email": "tiara@tiara.com",
    "us_contrasena": "pass123",
    "us_contacto": "987654321"
}

###Acceder a una ruta protegida, el token obtiene al realizar login
GET http://localhost:3000/pets/auth/protegido
Authorization: Bearer {{token}}

###DADWAW
GET http://localhost:3000/pets/perfil
Authorization: Bearer {{token}}


###Obtener todas las publicaciones
GET http://localhost:3000/pets/publicaciones

###Obtener todas las publicaciones
GET http://localhost:3000/pets/verDetalles/10

###Crear una publicacion
POST http://localhost:3000/pets/publicaciones/crear
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "pu_titulo": "Cara",
  "pu_descripcion": "Rostro humano",
  "pu_ubicacion": "Arica",
  "pu_imagen": "cara.png",
  "pu_imagenes": [
    "olo.png",
    "wwos.png"
  ],
  "pu_etiquetas": [
    1,
    3
  ]
}

###Obtener todas las etiquetas
GET http://localhost:3000/pets/tags

###Obtener todas las publicaciones
GET http://localhost:3000/pets/posts


